config/routes.rb
Rails.application.routes.draw do

  devise_for :employees, controllers: { registrations: "registrations"}
  get 'welcome/index'
  resources :admins
  resources :schedules

  get 'admins/:id/report' => "admins#report"
  get 'admins/:id/doReport' => "admins#doReport"
  get 'admins/:id/doReportDays' => "admins#doReportDays"

  get 'schedules/:id/report' => 'schedules#report'

  authenticated :employee do
    root 'schedules#index', as: "authenticated_root"
  end

  root 'welcome#index'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :first_name
  validates_presence_of :last_name
  has_many :schedules

  def self.get_employee_review params
    hash = Hash.new
    today = DateTime.now.to_date
    #simulation of first payday
    #today = today - (today.day - 13).days
    payday_one = 15
    payday_two = today.end_of_month.day
    if check_available? payday_one, payday_two
      hash[:available] = true
      if today.day < payday_one
        hash[:startDate] = today.beginning_of_month
        hash[:endDate] = today.beginning_of_month + 14.day
      else
        hash[:startDate] = (today - (today.day - 1).day) + 15.day
        hash[:endDate] = today.end_of_month
      end
      hash[:id] = params[:id]
      hash[:option] = "check"
      hash[:worked_days] = get_report hash
      return hash
    else
      hash[:available] = false
      return hash
    end
  end

  #getting the days of the employee abscence into a range of days
  #From To && Employee ID
  def self.get_report params #absence
    if params[:option] == "" || params[:option] == "check"
      return get_inputs_outputs assistance_day(params)
    else
      days = WorkingHours.new
      return days.absence_days params[:startDate], params[:endDate], params[:id]
    end
  end

  def self.assistance_day params
    if params[:startDate] != ""
      assits_days = Schedule.where("employee_id = ? and DATE(date) >= ? and DATE(date) <= ?",params[:id],params[:startDate], params[:endDate]).order(:date)
      #assits_days = assits_days[1]
    else
      assits_days = Schedule.where("employee_id = ? and DATE(date) = ?",params[:id],params[:startDate]).order(:date)
    end
    return assits_days #{:days => assits_days}
  end

  def self.get_inputs_outputs assits_days
    check = WorkingHours.new
    check.get_info_of_day assits_days
  end

  private

  def self.check_available? dayOne, dayTwo
    today = Time.now.beginning_of_day
    #simulation of first payday
    #today = today - (today.day - 13).days
    if !(dayOne - today.day == 3 || dayTwo - today.day == 3)
      return false
    else
      return true
    end
  end

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base

  belongs_to :employee

end

app/models/working_hours.rb
class WorkingHours

  #require 'business_time'

  #BusinessTime::Config.beginning_of_workday = "9:00 am"
  #BusinessTime::Config.end_of_workday = "6:00 pm"

  #http://stackoverflow.com/questions/4027768/calculate-number-of-business-days-between-two-days
  def absence_days startDate, endDate, employeeId
    business_days = []
    if startDate != "" && endDate != ""
      startDate = DateTime.parse(startDate)
      endDate = DateTime.parse(endDate)
      for i in 0..different_days(startDate, endDate) + 1
        current_day = startDate + i.days
        if (!current_day.saturday? && !current_day.sunday?) && fail_to_work?(employeeId, current_day)
          business_days << current_day
        end
      end
    end
    return business_days
  end

  def get_info_of_day assits_days
    hash = Hash.new
    #get the date & hour of the check-in & check-out turning that into an array
    days_array = []
    assits_days.each { |d| days_array << d.date }
    ######################################################################
    #puts assits_days.size.to_i
    if assits_days.size > 1
      hash = get_worked_days(days_array, hash)
    end
    return hash
  end

  def different_days startDate, endDate
    different_day = (((endDate.to_time - startDate.to_time) / 1.days) - 1 )
    different_day *= -1 if different_day < 0
    return different_day
  end

  private

  #%F - The ISO 8601 date format (%Y-%m-%d)
  def fail_to_work? employeeId, date
    Schedule.where("employee_id = ? and DATE(date) = ?",employeeId, date.strftime("%F")).size == 0
  end

  #http://www.tutorialspoint.com/ruby/ruby_date_time.htm
  #https://learnrubythehardway.org/book/ex32.html
  #Turning the cyclo
  def get_worked_days days_array, hash
    position = 0
    position2 = 1
    days_array.each do |d|
      if d.day != days_array[position].day
        hash = return_info hash, days_array[position], days_array[position2]
        position+=2
        position2+=2
      elsif days_array.index(d) == days_array.size - 1
      #  puts days_array.index(d)
        hash = return_info hash, days_array[position], days_array[position2]
      end
    end
    return hash
  end

  def return_info hash, check_in_hour, check_out_hour
    late = "09:30"
    earlyOne = "15:00"
    earlyTwo = "17:45"
    came_late = check_in_hour.strftime("%H:%M")
    if came_late >= late
      late_message = "came late!"
    end
    left_early = check_out_hour.strftime("%H:%M")
    if left_early >= earlyOne && left_early <= earlyTwo
      left_message = "left early!"
    end
    hash["#{check_in_hour.strftime("%F")}"] = { check_in: check_in_hour, check_out: check_out_hour, late: late_message, early: left_message}
    return hash
  end




end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController


  def index
    @employees = Employee.all
  end

=begin
  def show
  end
=end

  def report
    @employee = Employee.find(params[:id])
  end

  def doReport
    @working_days = Employee.get_report params
    render layout: false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:employee).permit(:first_name, :last_name, :email, :password, :password_confirmation)
	end

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController

  before_action :is_admin?
  before_action :find_schedule, only: [:show, :edit, :update]

  def index
    #@schedules = Schedule.where(user_id: current_employee).order("DESC")
    @employee = current_employee
  end

  def report
    if params[:id]
      @working_time = Employee.get_employee_review params
      if !@working_time[:available]
        flash[:message] = "You haven't permission to review your Schedule, only available three days before the paycheck day."
        render 'report'
      end
    else
      render 'index'
    end
  end

  def show

  end

  def new
    @schedule = current_employee.schedules.build
  end

  def create
    worktime1 = current_employee.schedules.build(date: DateTime.parse("#{params[:date]} #{params[:checkin]}"))
    worktime2 = current_employee.schedules.build(date: DateTime.parse("#{params[:date]} #{params[:checkout]}"))
    #@schedule = current_employee.schedules.build(schedule_params)

    if worktime1.save && worktime2.save
      #format.html { render 'index', notice: 'Schedule was successfully stored.' }
      flash[:notice] = "Schedule was successfully saved."
      #render 'index'
      redirect_to schedules_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @schedule.update(schedule_params)
      redirect_to @schedule
    else
      render 'edit'
    end
  end

  private

  def find_schedule
    @schedule = Schedule.find(params[:id])
  end

  def schedule_params
    params.require(:schedule).permit(:date)
  end


  def is_admin?
    if current_employee.admin?
      redirect_to admins_path
    end
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admins/doReport.html.haml
.wrapper_with_padding
  - if !@working_days.is_a? Array
    -#= @working_days
    %br
    - if !@working_days.to_a.any?
      %div{:class=>"alert alert-info text-center", :role=>"alert"} The user doesnt came to work for those dates
    %table.table.table-bordered
      %thead
        %th Date
        %th check-in
        %th check-out
        %th Came late?
        %th Left early?

      %tbody
        - @working_days.each do |key,value|
          %tr.text-center
            %td= key
            %td= value[:check_in].strftime("%H:%M %p")
            %td= value[:check_out].strftime("%H:%M %p")
            - unless value[:late].nil?
              %td{:class=>"danger"}= value[:late]
            - else
              %td
            - unless value[:early].nil?
              %td{:class=>"danger", :role=>"alert"}= value[:early]
            -else
              %td
  - else
    %br
    %div{:class=>"alert alert-info text-center", :role=>"alert"} Days that not came to work: #{@working_days.size}

    %table.table.table-bordered
      %thead
        %tr
          %th Date
      %tbody
        - @working_days.each do |date|
          %tr
            %td= date.strftime("%F")

app/views/admins/index.html.haml
.wrapper_with_padding

  %h2 Admin Section

  %table.table.table-bordered
    %thead
      %tr
        %th ID
        %th Name
        %th Last Name
        %th Email
        %th Action

    %tbody
      - @employees.each do |employee|
        - unless employee.admin?
          %tr
            %td= employee.id
            %td= employee.first_name
            %td= employee.last_name
            %td= employee.email
            %td= link_to "report", "admins/#{employee.id}/report"

app/views/admins/report.html.haml
%link{:rel => "stylesheet", :href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"}
.wrapper_with_padding

  %h2 Report of #{@employee.first_name} #{@employee.last_name}

  .row
    .col-md-4
      .input-group
        %label From
        %input.date{:type=>"text", :id=>"startDate"}

    .col-md-4
      .input-group
        %label To
        %input.date{:type=>"text", :id=>"endDate"}

  .row
    .btn-group{:data_toggle=>"optionsReport"}
      %label.btn.btn-success.active
        %input{:type=>"radio", :name => "options", :id=>"check", :checked=>"true"}
          Assistance

      %label.btn.btn-success
        %input{:type=>"radio", :name => "options", :id=>"absence"}
          Absence

  .row
    .input-group
      %input{:type=>"hidden", :value=>@employee.id, :id=>"employeeId", :name=>"employeeId"}
      %input{:type=>"hidden", :id=>"option", :name=>"option"}

  #tableReport


=javascript_include_tag 'schedule_report'

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Textile.Co | Hugo
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  %link{:rel => "stylesheet", :href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"}
  = csrf_meta_tags
%body
  %header
    .header_inner
      = link_to "Textile.Co", root_path, id: "logo"
      %nav
        - if employee_signed_in?
          = link_to "New Schedule", new_schedule_path
          = link_to "Sign Out", destroy_employee_session_path, method: :delete
        - else
          = link_to "Log In", new_employee_session_path

  %p.notice= notice
  %p.alert= alert

  = yield

app/views/schedules/_form.html.haml
%link{:rel => "stylesheet", :href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"}
= simple_form_for @schedule do |f|

  .input-group
    = f.input :date, as: :string, label: "Date", input_html: { class: 'date', id: 'date', name: 'date' }

  .input-group
    = f.input :date, as: :string, label: "Check In", input_html: { class: 'time', id: "checkin", name: "checkin" }

  .input-group
    = f.input :date, as: :string, label: "Check Out", input_html: { class: 'time', id: "checkout", name: "checkout" }

  %br
  = f.button :submit

:javascript
  $(function() {

    $(".time").datetimepicker({format: "LT"});
    $(".date").datepicker({format: "yyyy-mm-dd", autoclose: true})

  });

app/views/schedules/edit.html.haml
.wrapper_with_padding
  %h2 Edit your Schedule

  = render 'form'

  = link_to "Cancel", schedule_path

app/views/schedules/index.html.haml
.wrapper_with_padding
  #schedules.clearfix
    %h2 Add a Schedule
    %button= link_to "New Schedule", new_schedule_path
    %p
    %button= link_to "Review Schedule Here!", "schedules/#{@employee.id}/report"

app/views/schedules/new.html.haml
.wrapper_with_padding
  %h2 Add your Check-in & Check-out

  = render 'form'

app/views/schedules/report.html.haml
.wrapper_with_padding

  -#= @working_time

  - if !flash.empty?
    #id
      - flash.each do |key, value|
        %h3= flash[key]

  - else

    - if !@working_time[:worked_days].to_a.any?
      %div{:class=>"alert alert-info text-center", :role=>"alert"} The user doesnt came to work for this fortnight

    %br

    %table.table.table-bordered
      %thead
        %th Date
        %th check-in
        %th check-out

      %tbody
        - @working_time[:worked_days].each do |key,value|
          %tr.text-center
            %td= key
            %td= value[:check_in].strftime("%H:%M %p")
            %td= value[:check_out].strftime("%H:%M %p")

app/views/schedules/show.html.haml
.wrapper_with_padding
  %h2 Your Check In & Check Out was successfuly recorded

  %p= @schedule.date

  = link_to "Home", schedules_path

  = link_to "Edit", edit_schedule_path(@schedule)

app/views/welcome/index.html.haml
#banner
  .banner_content
    %h1 Textile.Co
    %p Large company with years of experience

#bottom_cta
  .wrapper
    %h2 New User
    %p If you want to sign up...
    %button= link_to "Click Meee!!!", new_employee_registration_path

%footer
  %p &copy; Hugo Lopez